---
title: 'RMarkdown:  In Class Assignment'
author: "PRECIOUS MERENU "
date: "Data 2401"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
  ## Everything above this is R code that we need to make the file run! We'll discuss it next class.
```

Reminder: We learned how to do these things in class today, but there is
a "Markdown Help" page available in RStudio (and lots of help if you
google).

# In-class Activity, Markdown

**Do not skip reading this line** Create a new section at the end of
this file with the title "Your work here", and beneath it, do the
following 3 things. To turn this in, make sure you've committed and
pushed, and turn in the link to this repository to the assignment on
Blackboard.

1.  Make a subsection called Wise words. Put your favorite quote in a
    block quote. Add a functioning link to a website that provides more
    information about that quote.

2.  Make a subsection called My semester. Make a three column table of
    the current courses you are taking, with separate columns for course
    number (put those in **bold**), course title (put those in
    *italics*), and instructor name.

3.  Lastly, make subsection called "I recommend", and add some
    information about your favorite author or musician.

-   A *subsubheading* with the name of the artist or author;\
-   An example of their writing or lyrics (formatted in a *block of
    text*);\
-   A *list* of things they have written or performed (remember to use
    the formatting markup for a list!).

Note that you can click "Knit" as you go along to see what the final
results are going to look like. The knitting will produce an html file,
which you will also need to stage/commit/push once it exists!

**Once you're done, remember to commit the changes and push the repo
back to your assignment on GitHub!**

# Your work here

## Wise words --"You fell down yesterday, stand up today." - H.G. Wells [the link text](https://www.brainyquote.com/quote_of_the_day)

## My Semester

| **Col 1 Course Number** | *Col 2 Courses* | The name of the Instructor of the Courses |
|:---|:---|:---|
| **DATA 2401** | *Data Science I* | Katherine Shoemaker |
| **CS 1411** | *Intro to Computer Science with Python* | Pablo Guillen |
| **GEOL 1308** | *History of the Earth* | Reyhan Koshkarly |
| **Math 2305** | *Discrete Math* | Mitsue Nakamura |
| **Math 2402** | *Calc II* | Plamen Simeonov |

## I Recommend

### SZA

**When you do your best you ca—, I done told you** **When you do your
best, hell, that's all you can do** **You and me and anybody else** **So
they always start talkin'**

**I'm runnin' away from where I'm from** **Never can stay with no one**
**Lovin' you almost feels like somethin'** **When no one's around me**
**You lost and found me** **I was surrounded** **With open, open, open**

**Open arms (Ooh), open arms** **You give me open, I'm so devoted**
**You keep me open (Ooh), open arms** **I'm so devoted to you, to you,
to you**

-   30 for 30 (w Kendrick Lamar)
-   Nobody Gets Me
-   Good days
-   My turn
